spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"

---
spring:
  config:
    activate:
      on-profile: "local"

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

logging:
  level:
    root: info
    web: info
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: trace

---
spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

logging:
  level:
    root: info
    web: info
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: trace

server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: "prod"

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

logging:
  level:
    root: info
    web: info
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: trace

springdoc:
  swagger-ui:
    enabled: false

server:
  port: 7102

---
spring:
  config:
    activate:
      on-profile: "common"

  mvc:
    log-request-details: false

jwt:
  properties:
    secret: yohwan
    expiredAt: 43200000 # 30 * 60000 30분  60000ms(1분)
    refreshExpiredAt: 604800000 # 7 * 24 * 60 * 60000 7일

server:
  shutdown: graceful
  error:
    whitelabel:
      enabled: false

solapi:
  properties:
    apiKey: nodata
    apiSecretKey: nodata
    domain: nodata
    pfId: nodata
    firstTemplateId: nodata
    secondTemplateId: nodata
    from: nodata